{{- $ca := genCA (printf "%s-storage-service-ca" (include "perforator.fullname" .)) 3650 }}
{{- $hostname := .Values.storage.hostname }}
{{- if $hostname }}
{{- if contains ":" $hostname }}
  {{- $hostname = index (regexSplit ":" $hostname -1) 0 }}
{{- end }}
{{- else }}
{{- $hostname = (printf "%s-storage-service" (include "perforator.fullname" .)) }}
{{- end }}
{{- $storageCert := genSignedCert $hostname nil (list $hostname) 3650 $ca }}
{{- $storageSecretName := printf "%s-storage-crt" (include "perforator.fullname" .) }}
apiVersion: v1
data:
  tls.crt: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "tls.crt" "defaultVal" $storageCert.Cert) }}
  tls.key: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "tls.key" "defaultVal" $storageCert.Key) }}
  ca.crt: {{ include "perforator.secrets.lookup" (dict "nameSpace" .Release.Namespace "secretName" $storageSecretName "key" "ca.crt" "defaultVal" $ca.Cert) }}
kind: Secret
metadata:
  name: {{ $storageSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
